name: Karsa Jobs UI CI
on:
  push:
    branches: [ "karsajobs-ui" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Lint Dockerfile
      - uses: action/checkout@v3
      - name: lint-dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      # 2. Build & Push
      - name: build-app-karsajobs-ui
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ github.actor }}/karsajobs-ui:latest .
          docker push ghcr.io/${{ github.actor }}/karsajobs-ui:latest
